name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # This runs on GitHub's Ubuntu runner

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build Email Service
      run: mvn clean package -DskipTests
      working-directory: ./MicroservicesBackend/emailservice/

    - name: Build Auth Server
      run: mvn clean package -DskipTests
      working-directory: ./MicroservicesBackend/authserver/

    - name: Build Eureka Server
      run: mvn clean package -DskipTests
      working-directory: ./MicroservicesBackend/eurekaserver/

    - name: Build Fare Calculation Service
      run: mvn clean package -DskipTests
      working-directory: ./MicroservicesBackend/farecalculationservice/

    - name: Build Payment Gateway Service
      run: mvn clean package -DskipTests
      working-directory: ./MicroservicesBackend/paymentgatewayservice/

    - name: Build Ride Matching Service
      run: mvn clean package -DskipTests
      working-directory: ./MicroservicesBackend/ridematchingservice/

    - name: Build User Management Service
      run: mvn clean package -DskipTests
      working-directory: ./MicroservicesBackend/usermanagementservice/

    - name: Build Docker images
      run: |
        docker build -t niketpadole06@gmail.com/smt_repo:eurekaserver1 ./eurekaserver
        docker build -t niketpadole06@gmail.com/smt_repo:usermanagementservice1 ./usermanagementservice
        docker build -t niketpadole06@gmail.com/smt_repo:authserver1 ./authserver
        docker build -t niketpadole06@gmail.com/smt_repo:ridematchingservice1 ./ridematchingservice
        docker build -t niketpadole06@gmail.com/smt_repo:paymentgatewayservice ./paymentgatewayservice
        docker build -t niketpadole06@gmail.com/smt_repo:emailservice ./emailservice
        docker build -t niketpadole06@gmail.com/smt_repo:farecalculationservice ./farecalculationservice

    - name: Push Docker images
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push niketpadole06@gmail.com/smt_repo:eurekaserver1
        docker push niketpadole06@gmail.com/smt_repo:usermanagementservice1
        docker push niketpadole06@gmail.com/smt_repo:authserver1
        docker push niketpadole06@gmail.com/smt_repo:ridematchingservice1
        docker push niketpadole06@gmail.com/smt_repo:paymentgatewayservice
        docker push niketpadole06@gmail.com/smt_repo:emailservice
        docker push niketpadole06@gmail.com/smt_repo:farecalculationservice

    - name: Deploy to EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$EC2_KEY" > key.pem
        chmod 600 key.pem

        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull niketpadole06@gmail.com/smt_repo:eurekaserver1
          docker pull niketpadole06@gmail.com/smt_repo:usermanagementservice1
          docker pull niketpadole06@gmail.com/smt_repo:authserver1
          docker pull niketpadole06@gmail.com/smt_repo:ridematchingservice1
          docker pull niketpadole06@gmail.com/smt_repo:paymentgatewayservice
          docker pull niketpadole06@gmail.com/smt_repo:emailservice
          docker pull niketpadole06@gmail.com/smt_repo:farecalculationservice

          docker-compose -f /home/ec2-user/docker-compose.yml up -d
        EOF
